""" Even Fibonacci
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
      1,2,3,5,8,13,21,34,55,89,...
    By considering the terms in the Fibonacci sequence whose values do not exceed four
    million, find the sum of the even-valued terms.
"""

"""
   make a list
   go through the list one by one
     add to the total
     check that the total isn't past 4,000,000
   find the sum of the even-valued terms
"""

def fibonacci(number):
    
    
    index=0
    total=0
    mylist=[1,2]
    while(total<number):
        total = total + mylist[index]
        index = index + 1
        mynewvalue = mylist[index] + mylist[index-1]
        mylist.append(mynewvalue)
        print mylist

    return total


if __name__ == "__main__":
	print fibonacci(4000000)
    #print fibonacci(4000000)